<?php
/**
 * File Name: SettingController.php
 * Automatically generated by QGC tool
 * @date: 2021-05-23 16:16:48
 * @version: 4.0.4
 */

namespace qh4module\setting;


use qh4module\setting\external\ExtSetting;
use qh4module\setting\models\setting\Index;
use qh4module\setting\models\setting\Create;
use qh4module\setting\models\setting\Update;
use qh4module\setting\models\setting\Delete;
use qh4module\setting\models\setting\Detail;

/**
 * Class SettingController
 * @package qh4module\setting\controllers
 * 使用 \backend\models\SettingAd 对 \backend\models\SettingMd 进行增删改查操作
 */
trait TraitSettingController
{
    /**
     * @return ExtSetting
     */
    public function ext_setting()
    {
        return new ExtSetting();
    }

    /**
     * 分页获取数据
     * @return array [total,list,page,limit]
     */
    public function actionIndex()
    {
        $model = new Index([
            'external' => $this->ext_setting(),
        ]);

        return $this->runModel($model);
    }

    /**
     * 新增一条设置
     */
    public function actionCreate()
    {
        $model = new Create([
            'external' => $this->ext_setting(),
        ]);

        return $this->runModel($model);
    }

    /**
     * 更新单条设置
     */
    public function actionUpdate()
    {
        $model = new Update([
            'external' => $this->ext_setting(),
        ]);

        return $this->runModel($model);
    }

    /**
     * 删除多条设置
     */
    public function actionDelete()
    {
        $model = new Delete([
            'external' => $this->ext_setting(),
        ]);

        return $this->runModel($model);
    }

    /**
     * 获取设置的详细信息
     * @return array
     */
    public function actionDetail()
    {
        $model = new Detail([
            'external' => $this->ext_setting(),
        ]);

        return $this->runModel($model);
    }
}