<?php
/**
 * File Name: Detail.php
 * Automatically generated by QGC tool
 * @date: 2021-05-23 19:52:49
 * @version: 4.0.4
 */

namespace qh4module\setting\models\setting;


use qh4module\setting\external\ExtSetting;
use qttx\web\ServiceModel;

/**
 * Class Detail
 * 获取tbl_setting表的单条数据详细信息
 * @package qh4module\setting\models\setting
 * @property ExtSetting $external
 */
class Detail extends ServiceModel
{
    /**
     * @var string|int 接收参数,必须：主键
     */
    public $id;
    
    /**
     * @inheritDoc
     */
    public function rules()
    {
        return [
            [['id'],'required'],
        ];
    }

    /**
     * @inheritDoc
     */
    public function run()
    {
        // 所有的字段,根据需要删减
        $fields = ['`ta`.`id`','`ta`.`type`','`ta`.`group`','`ta`.`key`','`ta`.`name`',
            '`ta`.`value`','`ta`.`update_by`', '`ta`.`update_time`','`ta`.`is_effective`',
            '`ta`.`effective_start_time`', '`ta`.`effective_end_time`',
            'tb.nick_name as update_by_name',
            ];

        $tb_set = $this->external->settingTableName();
        $tb_info = $this->external->userInfoTableName();
        $result = $this->external->getDb()
            ->select($fields)
            ->from("$tb_set as ta")
            ->leftJoin("$tb_info as tb", 'ta.update_by=tb.user_id')
            ->whereArray(['id'=>$this->id])
            ->row();

        if (empty($result)) {
            $this->addError('id', '查询条目不存在');
            return false;
        }

        $result['effective_time'] = [];
        if ($result['effective_start_time'] > 0) {
            $result['effective_time'][0] = $result['effective_start_time'];
        }else{
            $result['effective_time'][0] = null;
        }
        if ($result['effective_end_time'] > 0) {
            $result['effective_time'][1] = $result['effective_start_time'];
        }else{
            $result['effective_time'][1] = null;
        }


        return $result;
    }
}
