<?php
/**
 * File Name: SettingMd.php
 * Automatically generated by QGC tool
 * @date: 2021-05-23 16:11:28
 * @version: 4.0.4
 */

namespace qh4module\setting\models\setting;


use qh4module\setting\external\ExtSetting;
use qttx\web\ServiceModel;

/**
 * Class SettingMd
 * @package backend\models
 * @description 数据表tbl_setting的Validate模型
 * @property ExtSetting $external
 */
class SettingModel extends ServiceModel
{

    /**
     * {@inheritDoc}
     */
    public function rules()
    {
        return $this->mergeRules([
            [['id', 'update_time', 'is_effective', 'effective_start_time', 'effective_end_time', 'del_time'], 'integer'],
            [['type'],'integer','max'=>127],
            [['group', 'key', 'name'], 'string', ['max' => 200]],
            [['value'], 'string', ['max' => 2000]],
            [['update_by'], 'string', ['max' => 64]]
        ], $this->external->rules());
    }

    /**
     * {@inheritDoc}
     */
    public function attributeLangs()
    {
        return $this->mergeLanguages([
            'id' => 'ID',
            'type' => '类型',
            'group' => '分组',
            'key' => 'KEY',
            'name' => '名称',
            'value' => '值',
            'update_by' => '更新人',
            'update_time' => '更新时间',
            'is_effective' => '是否生效',
            'effective_start_time' => '生效的开始时间,0不限制',
            'effective_end_time' => '生效的结束时间,0不限制',
            'del_time' => 'delTime'
        ], $this->external->attributeLangs());
    }
}
